sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
install:
  - npm install
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
  local_dir: public
