# Blog info
blog_name: haifuns
slogan: Later equals never
url: https://haifuns.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: haifuns,后端,JAVA,架构,算法

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
#  - name: Project
#    url: /project/
#    target_blank: true #在新页面打开
  - name: Roaming
    url: /roaming/
    target_blank: false
  - name: Github
    url: https://github.com/haifuns
    target_blank: true
#  - name: Twitter
#    url: https://twitter.com/forsigner
#    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /categories/
    target_blank: false
  - name: 标签
    url: /tags/
    target_blank: false
  - name: 漫游
    url: /roaming/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Have fun ~

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
#blog_name_font_familiy: Lobster-Regular
#blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST  # HOME_NAV | POST

# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: d3c8edb388553a2084296cbfe9a0785a

# Comment service

# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: false # 如果使用 gitalk，请设置改之为true
  clientID:
  clientSecret:
  repo: blog-comment
  owner: forsigner
  admin: forsigner


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: masttnqEt9G69mj43i9oaA1C-gzGzoHsz # your leancloud application appid
  appkey: hgIx9VKn0GLDhRcLxQuNMl0E # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Say something # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "这个人很神秘，什么都没写"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@haifuns"
    text_value_url: https://github.com/haifuns
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "haifuns@163.com"
  - type: location
    icon: icon-location
    text_value: 北京

link:
#  - name: 织网
#    info: 身体和灵魂，总有一个在路上
#    url: http://zheng-ji.info/
#    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100


project:
#  - type: personal
#    name: fexo
#    url: https://github.com/forsigner/fexo
#    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo

roaming:
  - year: 2022
    list:
      - type: book
        date: "03-16"
        text_value: "2010：太空漫游"
      - type: movie
        date: "02-07"
        text_value:  狙击手 
      - type: movie
        date: "02-06"
        text_value:  这个杀手不太冷静
      - type: movie
        date: 
        text_value:  波西米亚狂想曲
      - type: movie
        date: 
        text_value:  扬名立万
      - type: movie
        date: 
        text_value:  猎杀T34
      - type: movie
        date: 
        text_value: 横道世之介
      - type: movie
        date: 
        text_value:  开端
      - type: movie
        date: 
        text_value:  夏日大作战
  - year: 2021
    list:
      - type: book
        date:
        text_value: 不能承受的生命之轻
      - type: book
        date:
        text_value: 无名之町
      - type: book
        date:
        text_value: 鼠疫
      - type: book
        date:
        text_value: 代码整洁之道
      - type: book
        date:
        text_value: 凤凰架构：构建可靠的大型分布式系统
      - type: book
        date:
        text_value: "2001: 太空漫游"
      - type: book
        date:
        text_value: 深入理解Kafka：核心设计与实践原理
      - type: movie
        date:
        text_value:  狙击手 
      - type: movie
        date:
        text_value: 新世界
      - type: movie
        date:
        text_value:  芬奇 Finch
      - type: movie
        date:
        text_value:  尚气与十环传奇
      - type: movie
        date:
        text_value:  头号玩家
      - type: movie
        date:
        text_value:  X特遣队：全员集结 The Suicide Squad (2021)
      - type: movie
        date:
        text_value:  摩加迪沙 모가디슈 (2021)
      - type: movie
        date: 10-24
        text_value:  沙丘 
      - type: movie
        date:
        text_value:  穆赫兰道
      - type: movie
        date:
        text_value:  贫民窟的百万富翁
      - type: movie
        date: 10-02
        text_value:  长津湖 
      - type: movie
        date:
        text_value:  四月物语
      - type: movie
        date:
        text_value:  情书
      - type: movie
        date:
        text_value:  基地
      - type: movie
        date:
        text_value:  一代宗师
      - type: movie
        date:
        text_value:  鬼灭之刃 剧场版 无限列车篇
      - type: movie
        date:
        text_value:  鱿鱼游戏
      - type: movie
        date:
        text_value:  白蛇2：青蛇劫起
      - type: movie
        date:
        text_value:  EVA 新世纪福音战士新剧场版3.33：Q
      - type: movie
        date:
        text_value:  EVA 新世纪福音战士新剧场版2.22：破
      - type: movie
        date:
        text_value:  EVA 新世纪福音战士新剧场版1.11：序
      - type: movie
        date:
        text_value:  新·福音战士剧场版：终 シン・エヴァンゲリオン劇場版:│▌ (2021)
      - type: movie
        date:
        text_value:  花束般的恋爱 
      - type: movie
        date:
        text_value:  浪客剑心 最终章 追忆篇 るろうに剣心 最終章 The Beginning 
      - type: movie
        date:
        text_value:  头领
      - type: movie
        date:
        text_value:  与我跳舞
      - type: movie
        date:
        text_value:  唇上之歌
      - type: movie
        date:
        text_value:  时光尽头的恋人
      - type: movie
        date:
        text_value:  橘色奇迹
      - type: movie
        date:
        text_value:  四重奏
      - type: movie
        date:
        text_value:  阳光姐妹淘
      - type: movie
        date: 05-08
        text_value:  悬崖之上 
      - type: movie
        date:
        text_value:  无罪之罪
      - type: movie
        date: 04-28
        text_value:  指环王：双塔奇兵 
  - year: 2020
    list:
      - type: book
        date: 02-21 23:30 - 02-22 04:00
        text_value: 告白 凑かなえ  
      - type: book
        date: 03-06
        text_value: 球状闪电刘慈欣      
      - type: book
        date: 03-13
        text_value:  超新星纪元 刘慈欣
      - type: book
        date:
        text_value:  时间移民刘慈欣 
      - type: book
        date:
        text_value:  带上她的眼睛刘慈欣 
      - type: book
        date:
        text_value:  梦之海刘慈欣 
      - type: book
        date:
        text_value:  局外人 加缪
      - type: movie
        date:
        text_value: 了不起的盖茨比 02-13
      - type: movie
        date:
        text_value: 想见你 02-15
      - type: movie
        date:
        text_value:  超体 02-24
      - type: movie
        date:
        text_value:  阿丽塔:战斗天使 03-02
      - type: movie
        date:
        text_value:  2001太空漫游 03-07
      - type: movie
        date:
        text_value: 2010太空漫游 03-07
      - type: movie
        date:
        text_value: 东京大饭店E11 03-21
      - type: movie
        date:
        text_value: 指环王+霍比特人 6部曲 04-05
      - type: movie
        date:
        text_value: 环形物语 04-13
      - type: movie
        date:
        text_value: 利刃出鞘05-02
      - type: movie
        date:
        text_value: 环太平洋：雷霆再起 05-03
      - type: movie
        date:
        text_value: 纸钞屋S1-2
      - type: movie
        date:
        text_value: 请回答1988
      - type: movie
        date:
        text_value: 天气之子 05-30
      - type: movie
        date:
        text_value: 迷失东京 06-06
      - type: movie
        date:
        text_value: 绝杀慕尼黑06-12
      - type: movie
        date:
        text_value: 与君相恋100次 06-24
      - type: movie
        date:
        text_value: 明日的我与昨日的你约会 06-26
      - type: movie
        date:
        text_value: 晚春 07-02
      - type: movie
        date:
        text_value: 何以为家
      - type: movie
        date:
        text_value: 爆裂鼓手 07-09
      - type: movie
        date:
        text_value: 社交网络 07-10
      - type: movie
        date:
        text_value: 流浪猫鲍勃 07-11
      - type: movie
        date:
        text_value: 知晓天空之蓝的人啊 08-22
      - type: movie
        date:
        text_value: 沉睡魔咒2 10-07
      - type: movie
        date:
        text_value: 后会无期 10-08
      - type: movie
        date:
        text_value: 康斯坦丁 10-11
      - type: movie
        date:
        text_value: 疯狂的麦克斯4：狂暴之路
      - type: movie
        date:
        text_value: 半泽直树S1 10-30
      - type: movie
        date:
        text_value: 八佰 10-31
      - type: movie
        date:
        text_value: "1917"
      - type: movie
        date:
        text_value: 小妇人 11-3
      - type: movie
        date:
        text_value: 半泽直树2 11-6
      - type: movie
        date:
        text_value: 国王的演讲 11-13
      - type: movie
        date:
        text_value: 姜子牙 11-20
      - type: movie
        date:
        text_value: 机动搜查队404
      - type: movie
        date:
        text_value: 信条
      - type: movie
        date:
        text_value: 中国女排 12-27
